title: "Volunteers on Wheels"
email: adamr@volunteersonwheels.org.uk
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/vow-logo-only.svg'
favicon: 'assets/images/vow-logo-only.svg'
author: Sal
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-CB78JLNGJP

# Authors
authors:
  peter:
    name: Peter Phillips
    display_name: Peter Phillips
    avatar: 'assets/images/peter-phillips.jpeg'
    email: adamr@volunteersonwheels.org.uk
    web: https://www.volunteersonwheels.org.uk
    description: "Founder and chair of trustees of Volunteers on Wheels. Peter is a dedicated philanthropist with a heart for giving back. A retired chartered surveyor, he brings a wealth of experience from serving as a trustee for several other charities."
  marcus:
    name: Marcus Ardeman
    display_name: Marcus Ardeman
    avatar: 'assets/images/marcus-ardeman.jpeg'
    email: adamr@volunteersonwheels.org.uk
    web: https://www.volunteersonwheels.org.uk
    description: "A philanthropist since his teenage years, Marcus has always been passionate about giving back to his community. He is a founding member of Volunteers on Wheels and brings a wealth of experience, dedication, and passion to our team."
  mary:
    name: Mary McDonagh
    display_name: Mary McDonagh
    avatar: 'assets/images/mary-mcdonagh.jpeg'
    email: adamr@volunteersonwheels.org.uk
    web: https://www.volunteersonwheels.org.uk
    description: "Mary's journey began during pandemic furlough, leading to years of hands-on experience with food banks and vulnerable communities. Her practical insights are invaluable to our operations."
  gary:
    name: Gary Weinstein
    display_name: Gary Weinstein
    avatar: 'assets/images/gary-weinstein.jpeg'
    email: adamr@volunteersonwheels.org.uk
    web: https://www.volunteersonwheels.org.uk
    description: "A lifelong community volunteer, Gary brings experience from synagogue leadership and the Ambulance Wish Foundation. His dedication to helping others spans decades."

# Social
social:
  instagram: https://www.instagram.com/volunteersonwheels
  facebook: https://www.facebook.com/groups/263700395180167
  twitter: https://twitter.com/volunteersonwheels

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-redirect-from
